___________________________________________________________________

### Nama : Shafira Octafia
### NIM    : 2109106023

### POSTTEST 7 KECERDASAN BUATAN
____________________________________________________________________


------------------------------------------------------------------------
### Import Library
------------------------------------------------------------------------

In [1]:
import tensorflow as tf

------------------------------------------------------------------
### Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor.
------------------------------------------------------------------

In [2]:
random_tensor = tf.random.normal([5,5])
random_tensor.numpy()

array([[-0.3220609 , -0.08344333,  1.3176668 ,  0.15323028,  1.1481619 ],
       [ 0.96934086,  1.2273245 , -1.2606068 , -0.9355057 , -0.15194264],
       [ 0.23491187, -0.35050672,  0.5650251 , -0.00869344,  1.9004605 ],
       [ 1.2529993 , -1.1940279 ,  0.3078881 ,  0.61891717,  0.9613365 ],
       [ 0.34918466,  0.24141505,  1.7705227 ,  0.3498441 , -0.08316787]],
      dtype=float32)

--------------------------------------------------------------------
### Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor.
--------------------------------------------------------------------

In [3]:
prime_tensor = tf.constant([2, 3, 5, 7, 11, 
                            13, 17, 19, 23, 29,
                            31, 37, 41, 43, 47, 
                            53, 59, 61, 67, 71, 
                            73, 79, 83, 89, 97], shape=[5,5], dtype=tf.float32)
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)

----------------------------------------------------------------------
### Tampilkan dimensi dari kedua variable tersebut.
-----------------------------------------------------------------------

In [4]:
# Menampilkan Dimensi Random_Tensor
dimensi_random = tf.constant(['random_tensor'], shape=[5,5])
dimensi_random.shape

TensorShape([5, 5])

In [5]:
tf.shape(dimensi_random)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

In [6]:
# Menampilkan Dimensi Primer_Tensor
dimensi_prime = tf.constant(['prime_tensor'], shape=[5,5])
dimensi_prime.shape

TensorShape([5, 5])

In [7]:
tf.shape(dimensi_prime)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

----------------------------------------------------------------------
### Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator).
-------------------------------------------------------------------------

--------------------------------------------------------------------
#### Operator Penjumlahan
---------------------------------------------------------------------

In [11]:
print("----------------------------------------------------------")
print("  Hasil Dari Penjumlahan Random_Tensor Dan Primer_Tensor  ")
print("----------------------------------------------------------")
penjumlahan = random_tensor + prime_tensor
penjumlahan.numpy()

----------------------------------------------------------
  Hasil Dari Penjumlahan Random_Tensor Dan Primer_Tensor  
----------------------------------------------------------


array([[ 1.677939 ,  2.9165566,  6.317667 ,  7.15323  , 12.148162 ],
       [13.969341 , 18.227325 , 17.739393 , 22.064495 , 28.848057 ],
       [31.234911 , 36.649494 , 41.565025 , 42.991306 , 48.90046  ],
       [54.253    , 57.805973 , 61.307888 , 67.61892  , 71.961334 ],
       [73.34918  , 79.24142  , 84.77052  , 89.349846 , 96.91683  ]],
      dtype=float32)

--------------------------------------------------------------------
#### Operator Pengurangan
-------------------------------------------------------------------

In [12]:
print("----------------------------------------------------------")
print("  Hasil Dari Pengurangan Random_Tensor Dan Primer_Tensor  ")
print("----------------------------------------------------------")
pengurangan = random_tensor - prime_tensor
pengurangan.numpy()

----------------------------------------------------------
  Hasil Dari Pengurangan Random_Tensor Dan Primer_Tensor  
----------------------------------------------------------


array([[ -2.3220608,  -3.0834434,  -3.6823332,  -6.84677  ,  -9.851838 ],
       [-12.030659 , -15.7726755, -20.260607 , -23.935505 , -29.151943 ],
       [-30.765089 , -37.350506 , -40.434975 , -43.008694 , -45.09954  ],
       [-51.747    , -60.194027 , -60.692112 , -66.38108  , -70.038666 ],
       [-72.65082  , -78.75858  , -81.22948  , -88.650154 , -97.08317  ]],
      dtype=float32)

---------------------------------------------------------------------
#### Operator Pembagian
--------------------------------------------------------------------

In [13]:
print("----------------------------------------------------------")
print("    Hasil Dari Pembagian Random_Tensor Dan Primer_Tensor  ")
print("----------------------------------------------------------")
pembagian = random_tensor / prime_tensor
pembagian.numpy()

----------------------------------------------------------
    Hasil Dari Pembagian Random_Tensor Dan Primer_Tensor  
----------------------------------------------------------


array([[-1.6103046e-01, -2.7814442e-02,  2.6353335e-01,  2.1890040e-02,
         1.0437835e-01],
       [ 7.4564680e-02,  7.2195560e-02, -6.6347726e-02, -4.0674161e-02,
        -5.2394015e-03],
       [ 7.5778025e-03, -9.4731543e-03,  1.3781100e-02, -2.0217296e-04,
         4.0435329e-02],
       [ 2.3641497e-02, -2.0237761e-02,  5.0473455e-03,  9.2375698e-03,
         1.3539950e-02],
       [ 4.7833514e-03,  3.0558868e-03,  2.1331599e-02,  3.9308327e-03,
        -8.5740077e-04]], dtype=float32)

-----------------------------------------------------------------------
#### Operator Perkalian
-----------------------------------------------------------------------

In [14]:
print("----------------------------------------------------------")
print("    Hasil Dari Perkalian Random_Tensor Dan Primer_Tensor  ")
print("----------------------------------------------------------")
perkalian = random_tensor * prime_tensor
perkalian.numpy()

----------------------------------------------------------
    Hasil Dari Perkalian Random_Tensor Dan Primer_Tensor  
----------------------------------------------------------


array([[ -0.6441218 ,  -0.25032997,   6.588334  ,   1.0726119 ,
         12.629781  ],
       [ 12.601431  ,  20.864517  , -23.951529  , -21.51663   ,
         -4.406337  ],
       [  7.282268  , -12.968749  ,  23.166029  ,  -0.3738178 ,
         89.32164   ],
       [ 66.408966  , -70.44765   ,  18.781174  ,  41.46745   ,
         68.25489   ],
       [ 25.49048   ,  19.071789  , 146.95338   ,  31.136126  ,
         -8.067284  ]], dtype=float32)

--------------------------------------------------------------------
#### Operator Modulus
--------------------------------------------------------------------

In [16]:
print("----------------------------------------------------------")
print("    Hasil Dari Sisa Bagi Random_Tensor Dan Primer_Tensor  ")
print("----------------------------------------------------------")
modulus = random_tensor % prime_tensor
modulus.numpy()

----------------------------------------------------------
    Hasil Dari Sisa Bagi Random_Tensor Dan Primer_Tensor  
----------------------------------------------------------


array([[ 1.677939  ,  2.9165566 ,  1.3176668 ,  0.15323028,  1.1481619 ],
       [ 0.96934086,  1.2273245 , 17.739393  , 22.064495  , 28.848057  ],
       [ 0.23491187, 36.649494  ,  0.5650251 , 42.991306  ,  1.9004605 ],
       [ 1.2529993 , 57.805973  ,  0.3078881 ,  0.61891717,  0.9613365 ],
       [ 0.34918466,  0.24141505,  1.7705227 ,  0.3498441 , 96.91683   ]],
      dtype=float32)

----------------------------------------------------------------
#### Operator Pemangkatan
---------------------------------------------------------------

In [18]:
print("----------------------------------------------------------------")
print("  Hasil Dari Pemangkatan Antara Random_Tensor Dan Primer_Tensor ")
print("----------------------------------------------------------------")
pemangkatan = random_tensor ** prime_tensor
pemangkatan.numpy()

----------------------------------------------------------------
  Hasil Dari Pemangkatan Antara Random_Tensor Dan Primer_Tensor 
----------------------------------------------------------------


array([[ 1.0372323e-01, -5.8099831e-04,  3.9721713e+00,  1.9834085e-06,
         4.5712438e+00],
       [ 6.6710585e-01,  3.2531925e+01, -8.1472878e+01, -2.1580820e-01,
        -1.8565662e-24],
       [ 3.1481402e-20, -1.4248365e-17,  6.8356071e-11, -0.0000000e+00,
         1.2775139e+13],
       [ 1.5537961e+05, -3.4982758e+04,  6.1939301e-32,  1.0949126e-14,
         6.0835272e-02],
       [ 4.3956854e-34,  0.0000000e+00,  3.9122330e+20,  0.0000000e+00,
        -0.0000000e+00]], dtype=float32)

----------------------------------------------------------------------
#### Pembagian Bulat
-----------------------------------------------------------------------

In [19]:
print("--------------------------------------------------------------------")
print("  Hasil Dari Pembagian Bulat Antara Random_Tensor Dan Primer_Tensor ")
print("--------------------------------------------------------------------")
pembagian_bulat = random_tensor // prime_tensor
pembagian_bulat.numpy()

--------------------------------------------------------------------
  Hasil Dari Pembagian Bulat Antara Random_Tensor Dan Primer_Tensor 
--------------------------------------------------------------------


array([[-1., -1.,  0.,  0.,  0.],
       [ 0.,  0., -1., -1., -1.],
       [ 0., -1.,  0., -1.,  0.],
       [ 0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.]], dtype=float32)

-----------------------------------------------------------------------
### Tampilkan nilai maksimum dan minimum dari variable random_tensor.
----------------------------------------------------------------------

--------------------------------------------------------------------
#### Nilai Maksimum Random_Tensor
--------------------------------------------------------------------

In [23]:
print("--------------------------------------------------------------------")
print("            Nilai Maksimum Random_Tensor Terletak Di Index          ")
print("--------------------------------------------------------------------")
max_random_tensor = tf.argmax(random_tensor, axis = 0)
max_random_tensor.numpy()

--------------------------------------------------------------------
            Nilai Maksimum Random_Tensor Terletak Di Index          
--------------------------------------------------------------------


array([3, 1, 4, 3, 2], dtype=int64)

In [24]:
print("--------------------------------------------------------------------")
print("             Nilai Minimum Random_Tensor Terletak Di Index          ")
print("--------------------------------------------------------------------")
min_random_tensor = tf.argmin(random_tensor, axis = 0)
min_random_tensor.numpy()

--------------------------------------------------------------------
             Nilai Minimum Random_Tensor Terletak Di Index          
--------------------------------------------------------------------


array([0, 3, 1, 1, 1], dtype=int64)

--------------------------------------------------------------------
### Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)
----------------------------------------------------------------------

In [25]:
concat_random_prime = tf.concat([random_tensor, prime_tensor], axis =0)
concat_random_prime

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-3.2206091e-01, -8.3443329e-02,  1.3176668e+00,  1.5323028e-01,
         1.1481619e+00],
       [ 9.6934086e-01,  1.2273245e+00, -1.2606068e+00, -9.3550569e-01,
        -1.5194264e-01],
       [ 2.3491187e-01, -3.5050672e-01,  5.6502509e-01, -8.6934371e-03,
         1.9004605e+00],
       [ 1.2529993e+00, -1.1940279e+00,  3.0788809e-01,  6.1891717e-01,
         9.6133649e-01],
       [ 3.4918466e-01,  2.4141505e-01,  1.7705227e+00,  3.4984410e-01,
        -8.3167873e-02],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
      

---------------------------------------------------------------------
### Tampilkan hasil sorting dari kedua variable di atas (descending)
--------------------------------------------------------------------

---------------------------------------------------------------------
#### Sorting  Random_Tensor secara Ascending
--------------------------------------------------------------------

In [26]:
print("--------------------------------------------------------------------")
print("                           Sorting Random_Tensor                    ")
print("--------------------------------------------------------------------")
desc_random_tensor = tf.sort(random_tensor, direction="DESCENDING")
desc_random_tensor.numpy()

--------------------------------------------------------------------
                           Sorting Random_Tensor                    
--------------------------------------------------------------------


array([[ 1.3176668 ,  1.1481619 ,  0.15323028, -0.08344333, -0.3220609 ],
       [ 1.2273245 ,  0.96934086, -0.15194264, -0.9355057 , -1.2606068 ],
       [ 1.9004605 ,  0.5650251 ,  0.23491187, -0.00869344, -0.35050672],
       [ 1.2529993 ,  0.9613365 ,  0.61891717,  0.3078881 , -1.1940279 ],
       [ 1.7705227 ,  0.3498441 ,  0.34918466,  0.24141505, -0.08316787]],
      dtype=float32)

----------------------------------------------------------------------
#### Sorting Prime_Tensor secara Ascending
---------------------------------------------------------------------

In [27]:
print("--------------------------------------------------------------------")
print("                           Sorting Random_Tensor                    ")
print("--------------------------------------------------------------------")
desc_prime_tensor = tf.sort(prime_tensor, direction="DESCENDING")
desc_prime_tensor.numpy()

--------------------------------------------------------------------
                           Sorting Random_Tensor                    
--------------------------------------------------------------------


array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)